#spring:
#  application:
#    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/product/**
#        - id: category-service
#          uri: lb://category-service
#          predicates:
#            - Path=/category/**
#      discovery:
#        locator:
#          enabled: true
##  zipkin:
##    base-url: ${ZIPKIN_URI:http://localhost:9411}
#server:
#  port: 8889
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
##    fetch-registry: 'true'
##    register-with-eureka: 'true'
##  instance:
##    prefer-ip-address: 'true'
##
##
##management:
##  endpoints:
##    web:
##      exposure:
##        include: "*"
##        exclude: info