version: "3.5"

services:

  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: deniz
      POSTGRES_DB: microservice
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

volumes:
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring