global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8002']
        labels:
          application: 'Product Service Application'
  - job_name: 'category-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8003' ]
        labels:
          application: 'Category Service Application'
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8889' ]
        labels:
          application: 'Api Gateway Service Application'
  - job_name: 'service-registry'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8761' ]
        labels:
          application: 'service Registry Application'